development:
  adapter: postgresql 
  pool: 5
  timeout: 5000
  database: ticketee_development 

test:
  adapter: postgresql 
  pool: 5
  timeout: 5000
  database: ticketee_test

production:
  adapter: postgresql 
  pool: 5
  timeout: 5000
  database: ticketee_production
