# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e6d92e2f46aa96f302cd12d82f15739cbb1413de0c2d9481b030a9e5d20e28b160561636aa6251152359ef75777606cbbc1bd13a1edba92aab25abf5db30b21

test:
  secret_key_base: abec75275534211369a3ae4eea06135e62b0f1e925df10ddc257559cce4cf736f10e74836259642af71f736a81d3e41f65fd2e9ac1fcc9f6b476d64416267e07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
